# Generated by Django 3.2.3 on 2021-08-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
